
FIND_PATH(HIDAPI_INCLUDE_DIR hidapi.h PATH_SUFFIXES  hidapi)
FIND_LIBRARY(HIDAPI_LIBRARY_LIBUSB  NAMES hidapi-libusb)
FIND_LIBRARY(HIDAPI_LIBRARY_HIDRAW  NAMES hidapi-hidraw)

MARK_AS_ADVANCED(HIDAPI_INCLUDE_DIR HIDAPI_LIBRARY_LIBUSB HIDAPI_LIBRARY_HIDRAW)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(HIDAPI
    REQUIRED_VARS HIDAPI_LIBRARY_LIBUSB HIDAPI_LIBRARY_HIDRAW HIDAPI_INCLUDE_DIR
)

IF(HIDAPI_FOUND)
    SET(HIDAPI_LIBRARIES ${HIDAPI_LIBRARY_LIBUSB} ${HIDAPI_LIBARRY_HIDRAW})
    SET(HIDAPI_INCLUDE_DIRS ${HIDAPI_INCLUDE_DIR})
ENDIF()

